#!/bin/bash

# touchpad
# this grep is not working under current system (root_upgrade11)
#if egrep -iq 'touchpad' /proc/bus/input/devices; then
  synclient VertEdgeScroll=0
  synclient TapButton1=1
  synclient TapButton2=3
  synclient TapButton3=2
  synclient LockedDrags=1
  synclient LockedDragTimeout=750
  synclient MaxTapTime=90 MaxDoubleTapTime=130 SingleTapTimeout=130
  synclient HorizScrollDelta=-18
  synclient VertScrollDelta=-112
  # synclient HorizTwoFingerScroll=1
  synclient HorizTwoFingerScroll=0
#fi

# keyboard
setxkbmap -layout "fr"
xset r rate 240 70

# disable screensaver (?)
( sleep 15s && xset -dpms && xset s noblank && xset s off ) &

# mouse
xset m default &
#xset m 14/10 7 & #razer

# i3 layout
ws1="1:1 "
ws2="2:2 "
ws3="3:3 "
ws4="4:4 "
ws5="5:5 "
ws6="6:6 "
ws7="7:7 "
ws8="8:8 "
ws9="9:9 "
ws10="10:10 "

# restore default layout
#i3-msg 'workspace "$ws1"; append_layout /home/rkj/.config/i3/layouts/default/ide.json'
#i3-msg 'workspace "$ws2"; append_layout /home/rkj/.config/i3/layouts/default/terminal.json'
#i3-msg 'workspace "$ws3"; append_layout /home/rkj/.config/i3/layouts/default/www.json'
#i3-msg 'workspace "$ws4"; append_layout /home/rkj/.config/i3/layouts/default/crypto.json'
#i3-msg 'workspace "$ws5"; append_layout /home/rkj/.config/i3/layouts/default/mail.json'
#i3-msg 'workspace "$ws9"; append_layout /home/rkj/.config/i3/layouts/default/media.json'
#i3-msg 'workspace "$ws10"; append_layout /home/rkj/.config/i3/layouts/default/monitor.json'


