#!/bin/sh

# debug
#set -o errexit
#readonly LOG="/home/rkj/log"
#exec 1>>$LOG
#echo i3-msg rename workspace $target to $1

target=$(i3-msg -t get_workspaces | jq -r 'map(select(.focused))[0].name')
i3-msg rename workspace $target to "$1"

